### ISSUE TITLE
Unstable start of welcome window and local table

### ISSUE THREAD

**Issue by simfann** [b0n541/jskat-multimodule#134] opened 2022-01-19 11:44 UTC
It's the first time I use the jskat program. I use newest jskat version 0.19.0, Windows 10 (newest update) and newest Java JDK and SRE. Starting a new program session the welcome window tends to remain uncomplete or comes very slowly to completion. Then the starting of a new table often only works, if I go into settings before. Otherwise there can be a program crash!
[Uncomplete welcome window](https://user-images.githubusercontent.com/79475795/150131063-580e09c0-960d-4b94-b59b-e607772b860d.jpg)

**Comment by b0n541** [comment] 2022-01-19 15:07
Thank you for reporting this. I'll have a look.

**Comment by b0n541** [comment] 2022-01-19 21:20
I deleted the complete directory <user-home>/.jskat and I couldn't reproduce the issue by starting JSkat the "first time" under Linux or Windows (running in VirtualBox). But nevertheless the startup code of JSkat is very old. Maybe there is a problem hidden somewhere.

Could you try to start JSkat from a command line interface with:

`java -jar JSkat....`

Or provide the log files stored at <user.home>/.jskat

**Comment by simfann** [comment] 2022-01-20 10:44
To create an actual logfile with a failure, I started program jskat today again. This time no "welcome" window appeared at all, although I have waited for at least 2 minutes. Then I have activated settings, left settings and "welcome" window appeared. Now I clicked "new table" and "start skat series" and the program worked well. Another time I started I have seen, that "welcome" window appeared when I navigated with my mouse pointer over the window. But then I couldn't start skat series by window. I used the menu and then program worked well. Attached the logfile.

[JSkat.log](https://github.com/b0n541/jskat-multimodule/files/7904438/JSkat.log)

**Comment by b0n541** [comment] 2022-01-20 19:34
The log file looks fairly normal.

I did a windows build with JDK 17 and the latest JavaFX version. Could you try whether this fixes the problem, please?

file:///home/jan/Downloads/JSkat-0.20.0-SNAPSHOT-all.jar

**Comment by b0n541** [comment] 2022-01-20 22:14
The log file looks o.k. to me.

I built a snapshot version from develop with JDK 17 and JavaFX 17. Could you try that out for me, please?

https://github.com/b0n541/jskat-multimodule/suites/5006520729/artifacts/146969605

**Comment by simfann** [comment] 2022-01-21 12:17
I have tried the snapshot version. It has the same behaviour as jskat 0.19.0!

**Comment by b0n541** [comment] 2022-01-21 17:38
I searched a bit and stumbled over this StackOverflow article:

https://stackoverflow.com/questions/61387601/javafx-stage-sometimes-appears-blank-on-win10

Maybe you have some 3D acceleration active that is not working with JavaFX. It's worth to try out this start parameter:

java -jar JSkat...jar -Dprism.order=sw

**Comment by simfann** [comment] 2022-01-21 18:13
Still the same behaviour. I believe now, that it could be a problem of my graphic card. What do you think about that? Strange to me is, that some or all buttons of "welcome" window appear, when I navigate with my mouse pointer over the window. Clicking of "start skat series" button also often doesn't work, but then it functions by menu. With workarounds like described before I always get jskat working.

**Comment by b0n541** [comment] 2022-01-21 20:29
I was hoping that using the "-Dprism.order=sw" parameter would help because it switches rendering from hardware to software rendering. I'm a bit out of ideas now to be honest.

I'll leave this issue open for a while anyways.

**Comment by simfann** [comment] 2022-01-22 10:21
I have now tested the best workaraound for my problems: Start jskat and now only use menu "skat table" for "Play on local table" and "start skat series". Then program works always finely for me. Perhaps my computer is too old (about 6 years) concerning graphic card and/or processor. Don't worry anymore, if I'm the only one with these problems!

**Comment by b0n541** [comment] 2022-01-22 11:54
I've seen that. The reported issue make me wonder whether the missing display of parts of the UI is caused by mixing Java Swing and JavaFX components together. 

I'll give it a try and migrate the main screen and the toolbar from Java Swing to JavaFX and look whether this fixes the problem for you.

**Comment by b0n541** [comment] 2022-01-22 21:06
I created a first preliminary version of a "JavaFX only" main window. Could you do me a favor to test whether everything is shown on start up now? If this works I know that I'm on the right path and that it's worth the effort to get rid of the Java Swing parts of the JSkat UI now.

https://github.com/b0n541/jskat-multimodule/suites/5027991076/artifacts/148215686

**Comment by simfann** [comment] 2022-01-23 12:47
That really had helped: The opening window appears at once and completely without any problem. But I can't start any routine. Is this because of preliminary version?

**Comment by b0n541** [comment] 2022-01-23 13:53
Yes, it starts a new game but the UI is not further updated, yet.

So this is good news then. I need to migrate all legacy Java Swing parts to JavaFX. This will take some time. I hope that you can live with the work around for version 0.19.0 meanwhile.

**Comment by simfann** [comment] 2022-01-23 15:27
That's o.k. Thanks!

**Comment by simfann** [comment] 2022-02-27 16:56
I just tried playing with JSkat 0.20.0. Now the program works on my pc very well. But there is still one small bug: Although I never have a hook on "Hide toolbar" at the start of the program, the toolbar won't appear until I go to "preferences" and set a hook on "Hide toolbar" and then reset the hook,

**Comment by b0n541** [comment] 2022-02-27 17:08
O.k., then I would propose to close this issue and open an dedicated one for the "Hide toolbar" issue?

**Comment by simfann** [comment] 2022-03-01 19:07
O.k., I close now this issue and make a new one about "Hide toolbar".

**Closed** 2022-03-01 19:07 UTC
Labels: bug
